project:
  title: "Introduction to R"
  output-dir: docs
  
author: "Jürgen Wilbert"
date: today
institute: "University of Münster"
  
execute: 
  echo: true
  warning: false  
  comment: ""
  freeze: auto
  
df-print: kable
embed-resources: true

format: 
  revealjs:
    scrollable: true
    theme: [style.scss]
    footer: "Jürgen Wilbert - Introduction to R"
    logo: images/logo-tree-transparent.png
    title-slide-attributes:
      data-background-image: images/bg-digital-data.jpg
