project:
  output-dir: html
  
df-print: kable

format: 
  revealjs:
    logo: /img/ZEIF.png
    scrollable: true
    theme: [style.scss]
    footer: "Jürgen Wilbert - Introduction to R"
    title-slide-attributes:
      data-background-color: "#a9bfd1"
