---
title: "Course announcement"
author: "Jürgen Wilbert"
date: "`r format(Sys.time(), '%d %B %Y')`"
format: html
---

```{r}
#| include: false
course_time <- "Thursday 16:15 - 17:45"
course_place <- "Orléans-Ring 12 - SRZ 104"
course_period <- c("23 October", "5 February")
course_title <- "Introduction to R"
course_moodle <- "<https://sso.uni-muenster.de/LearnWeb/learnweb2/course/view.php?id=89298>"
```

This semester I will be teaching a course on "`r course_title`"

**Topic**: Introduction to reproducible research and data analysis with the R software  
**Level**: We start at the very beginning.  
**Mode**: Biweekly in-person meetings and online materials (see learnweb course)  
**Time**: `r course_time`  
**Start**: `r course_period[1]`  
**End**: `r course_period[2]`\
**Place**: `r course_place`\
**Language**: English and German (depending on participants' German language skills)

### Requirements:

-   You need a computer, obviously :-)
-   The computer has to run current versions of R and R-Studio (except for the first session).

### Who can participate?

Anybody interested: students, PhD students, profs. ...

### Course materials

For updates on the course and to participate, please enroll to the moodle course:

`r course_moodle`

### Start

The first session will be on `r course_time`, `r course_period[1]`.

Topic:

-   Installation of R and R-Studio
-   The R-Studio environment
-   Introduction to the main idea of this course: reproducible research

All the best,

Jürgen Wilbert
